In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])

NameError: name 'a' is not defined

In [ ]:
for (i = 0; i < rows; i++): {
  for (j = 0; j < columns; j++): {
    c[i][j] = a[i][j]*b[i][j];
  }
}


In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a
ndarray=([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
a.shape
(3, 5)
a.ndim
2
a.dtype.name
'int64'
a.itemsize
8
a.size
15
type(a)
# <class 'numpy.ndarray'>
b = np.array([6, 7, 8])
b
array([6, 7, 8])
type(b)


In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

In [ ]:
from numpy import pi
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)

In [ ]:
a = np.arange(6)                    # 1d array
print(a)
[0 ,1 ,2, 3, 4, 5]

In [ ]:
print(np.arange(10000))

In [ ]:
print(np.arange(10000).reshape(100, 100))

In [ ]:
b = np.arange(12).reshape(3, 4)
b

In [ ]:
B = np.arange(3)
B


In [4]:
import numpy as np

In [6]:
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [9]:
f=np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [11]:
g=np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
h=np.linspace(0,10,num=5)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### 1-D array

In [15]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [16]:
b=np.zeros(2)
b

array([0., 0.])

In [17]:
c=np.ones(3)
c

array([1., 1., 1.])

### 2-D arrays

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# create an empty array with 2 elements
d=np.empty(3)
d

array([1., 1., 1.])

In [13]:
i=np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

### 3-D array

In [14]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
pip install numpy