### numpy practice session

In [2]:
# pip install numpy


# 1-D array
food = np.array(['pakora','samosa','Raita'])
food

### Creating an array using numpy

In [6]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [7]:
type(price)

numpy.ndarray

In [8]:
type(food)

numpy.ndarray

In [ ]:
len(food)

In [10]:
price[0:]

array([5, 5, 5])

In [12]:
food[1]

'samosa'

In [13]:
price.mean()

5.0

In [14]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
# empty
np.empty(10)

array([6.79038654e-313, 2.33419537e-312, 2.44029516e-312, 2.33419537e-312,
       9.76118064e-313, 2.33419537e-312, 2.44029516e-312, 1.12465777e-312,
       1.14587773e-312, 1.04718096e-142])

In [17]:
# sericfy
np.arange(2,20)


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [18]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# specific range or table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [22]:
# line space
np.linspace(0,10, num=40
        )


array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

In [25]:
# specify your data type
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
#for find missing values
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

### Array functions


In [28]:
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [29]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [30]:
b=np.array([10.3,3.3,53,6,91,6,45.5])
b

array([10.3,  3.3, 53. ,  6. , 91. ,  6. , 45.5])

In [31]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.3,   3.3,  53. ,   6. ,  91. ,   6. ,  45.5])

In [32]:
c.sort()
c

array([  0.5,   2. ,   3.3,   4. ,   6. ,   6. ,   6. ,  10. ,  10.3,
        10.3,  12. ,  15. ,  45.5,  53. ,  91. , 100. , 320. ])

### 2-D arrays

In [ ]:
a=np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

In [36]:
b=np.array([[6,7,5,6,2],[2,4,5,8,9]])
b

array([[6, 7, 5, 6, 2],
       [2, 4, 5, 8, 9]])

In [37]:
c=np.concatenate((a,b))
c

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [6, 7, 5, 6, 2],
       [2, 4, 5, 8, 9]])

In [41]:
c=np.concatenate((a,b),axis=1)
c

array([[1, 2, 3, 4, 5, 6, 7, 5, 6, 2],
       [5, 4, 3, 2, 1, 2, 4, 5, 8, 9]])

In [44]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [52]:
a=np.array([[[0,1,2,3],
             [4,5,6,7]],
            [[0,1,2,3],
            [4,5,6,7]],
            [[0,1,2,3],
            [4,5,6,7]]])
a 

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [54]:
#to din tohe number of dimention

a.ndim

3

In [56]:
b=np.array([[5,6,7],
           [8,9,10],
           [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [57]:
b.ndim

2

In [58]:
#size (number of elements)
a.size

24

In [59]:
#shape
a.shape


(3, 2, 4)

In [77]:
a= np.arange(9) #3*3=9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
# reshape
b=a.reshape(3,3) #3*3=9
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
# reshape
np.reshape(a,newshape=(1,9),order='c')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [86]:
# convert 1D into 2D
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a.shape

(9,)

In [96]:
# rowwise 2d
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [89]:
b.shape

(1, 9)

In [95]:
# column wise
c=a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [97]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [100]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [101]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [103]:
a.sum()

45

In [104]:
a.mean()

5.0

In [105]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]
